version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: RabbitMq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      # AMQ protocol port
      - "5672:5672"
      # Http Managent UI
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

    networks:
      - bridge
    extra_hosts:
      - host.docker.internal:host-gateway
  backend:
    image: agro_help
    restart: unless-stopped
    build: 
      context: .
    volumes:
      - .:/agro_help_container
    ports:
      - 8000:8000
    container_name: agrohelp_container
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
    name: network
