version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: culture_service
    ports:
      - '8002:8002'
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
    name: network