version: '3.8'
services:

  # Django application
  soils_management:
    image: soils_management
    restart: unless-stopped
    build: 
      context: .
    volumes:
      - .:/soils_management
    ports:
      - 8004:8004
    container_name: soils_container
    command: python manage.py runserver 0.0.0.0:8004
    networks:
      - bridge
  queue:
    build:
      context: .
    command: 'python -u consumer.py'
    depends_on:
      - soils_management
    restart: unless-stopped
    container_name: soil_consumer
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
    name: network