# Generated by Django 4.2 on 2023-05-30 13:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('composition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.soil')),
            ],
        ),
        migrations.CreateModel(
            name='SoilCulture',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_culture', to='core.culture')),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_culture', to='core.soil')),
            ],
            options={
                'unique_together': {('soil', 'culture')},
            },
        ),
    ]
