# Generated by Django 4.2 on 2023-06-03 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='category',
            field=models.CharField(default='cc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='culture',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
