# Generated by Django 4.2 on 2023-06-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_culture_category_culture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilculture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
