# Generated by Django 4.2 on 2023-07-03 10:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='culture')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('composition', models.TextField()),
                ('type', models.CharField(choices=[('orgnaic', 'organic'), ('chemical', 'chemical')], max_length=25)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fertilizers')),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('composition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the soil area', max_length=5000)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.soil')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('area', models.FloatField(help_text='in square meter')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CultureFilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizers', to='core.culture')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_fertilizer', to='core.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='CultureDiseaseAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease/')),
                ('disease_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('solution', models.TextField()),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_disease_advice', to='core.culture')),
            ],
        ),
        migrations.CreateModel(
            name='AgriculturePractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the agricultural practice', max_length=255)),
                ('practise', models.TextField()),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriculture_practice', to='core.culture')),
            ],
        ),
        migrations.CreateModel(
            name='SoilCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_culture', to='core.culture')),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_culture', to='core.soil')),
            ],
            options={
                'unique_together': {('soil', 'culture')},
            },
        ),
        migrations.CreateModel(
            name='CultureParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel', to='core.culture')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='core.parcel')),
            ],
            options={
                'unique_together': {('culture', 'parcel')},
            },
        ),
    ]
