version: '3.8'
services:
  parcel:
    image: agrohelp/parcel_service
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrohelp_parcel_service
    command: python run.py
    ports:
      - 8003:8003
    networks:
      - bridge
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py
    restart: unless-stopped
    container_name: agrohelp_parcel_consumer
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
    name: network