name: Account Service Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout
      - name: Build the Account Docker Service image
        run: |
          cd src/back-end/microservices/src/back-end/microservices/account_service
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
