name: Account Micro Service Docker Image

on:
  push:
    branches: ["main", "it"]
  pull_request:
    branches: ["main", "it"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Account Docker Service image
        run: |
          cd src/back-end/microservices/account_service
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
