name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends \
          build-essential \
          libpq-dev \
          libgeos-dev \
          libproj-dev \
          gdal-bin \
          libsqlite3-mod-spatialite \
          && rm -rf /var/lib/apt/lists/*
          python -m pip install --upgrade pip
          cd src/back-end/AgroHelp
          pip install -r requirements.txt
          python manage.py makemigrations
          python ./manage.py shell -c "import django;django.db.connection.cursor().execute('SELECT InitSpatialMetaData(1);')";
          python manage.py migrate
      - name: Run Tests
        run: |
          cd src/back-end/AgroHelp
          python manage.py test
