name: Django CI

on:
  push:
    branches: ["main", "it"]
  pull_request:
    branches: ["main", "it"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends \
          build-essential \
          libpq-dev \
          libgeos-dev \
          libproj-dev \
          gdal-bin \
          libsqlite3-mod-spatialite
          python -m pip install --upgrade pip
          cd src/back-end/AgroHelp
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd src/back-end/AgroHelp
          python manage.py test
