name: Docker Image CI

on:
  push:
    branches: ["main", "it"]
  pull_request:
    branches: ["main", "it"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          cd src/back-end/AgroHelp
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
