name: Publish Account Micro Service Docker Image
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Account Docker Service image
        run: |
          cd src/back-end/microservices/account_service && docker build . --tag ghcr.io/brownofdarkness/agrohelp_account_service:latest
          docker run ghcr.io/brownofdarkness/agrohelp_account_service:latest
          docker push ghcr.io/brownofdarkness/agrohelp_account_service:latest
